// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkM3J_AbNSEg6Qb56Tr3eTVxi9unoXxJc',
    appId: '1:601124639008:web:e08c63563aea0c8cf70745',
    messagingSenderId: '601124639008',
    projectId: 'projeto-laborial---virtnuvem',
    authDomain: 'projeto-laborial---virtnuvem.firebaseapp.com',
    databaseURL: 'https://projeto-laborial---virtnuvem-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'projeto-laborial---virtnuvem.appspot.com',
    measurementId: 'G-BLTHBYS60L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjZDXGV6ZtzsYE1uliv-bCgjs8hEYsemY',
    appId: '1:601124639008:android:acee515d5958a334f70745',
    messagingSenderId: '601124639008',
    projectId: 'projeto-laborial---virtnuvem',
    databaseURL: 'https://projeto-laborial---virtnuvem-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'projeto-laborial---virtnuvem.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBARcfd7HYxJR_v61EHq-pvinVLSnleX9k',
    appId: '1:601124639008:ios:10c9771e1d4ac551f70745',
    messagingSenderId: '601124639008',
    projectId: 'projeto-laborial---virtnuvem',
    databaseURL: 'https://projeto-laborial---virtnuvem-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'projeto-laborial---virtnuvem.appspot.com',
    iosBundleId: 'com.example.copia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBARcfd7HYxJR_v61EHq-pvinVLSnleX9k',
    appId: '1:601124639008:ios:a4b33b833fd10737f70745',
    messagingSenderId: '601124639008',
    projectId: 'projeto-laborial---virtnuvem',
    databaseURL: 'https://projeto-laborial---virtnuvem-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'projeto-laborial---virtnuvem.appspot.com',
    iosBundleId: 'com.example.copia.RunnerTests',
  );
}
